Rf 31 2 solve minor bugs
Gestion-de-Calidad-2021/SonarQube_Version_Albergue pull request #1
Opened 2021-09-23 16:16 UTC by JuanJoseQuiroga

Minor bugs fixed

2021-09-23 23:55 UTC, DanielCamSan requested changes
Por lo demas todo esta perfecto, solo ese pequeño cambio en el sonar.properties, puedes cambiarlo localmente si gustas, pero para evitar conflictos te pediria porfavor que lo cambies el nombre del proyecto y su key a su origianl en un commit mas

2021-09-23 23:55 UTC, DanielCamSan commented on sonar-project.properties
> +sonar.projectKey=ProyectoAlbergue
Seria ideal cambiar el nombre al original antes de hacer el pull request para no cambiar el nombre al proyecto de los demas compañeros

2021-09-24 01:14 UTC, Allen-Vargas requested changes
Revisar lo properties

2021-09-24 01:28 UTC, DanielCamSan approved these changes

2021-09-24 01:28 UTC, DanielCamSan commented on .scannerwork/report-task.txt
> -projectKey=Albergue
Borrar este archivo del commit , se lo añadira al git ignore posteriormente

2021-09-24 01:30 UTC, Allen-Vargas approved these changes

2021-09-24 01:31 UTC, merged